export const experiences = [
  {
    period: "Apr 2021 — Apr 2025",
    role: "Senior Software Engineer",
    company: "e-zest solutions",
    location: "Pune",
    description:
      "Leading frontend development for modern web applications, focusing on scalable architecture, reusable components and high-quality responsive experiences.",
    achievements: [
      // "Built and maintained production applications using React, Next.js and TypeScript.",
      // "Designed reusable component patterns that improved consistency across multiple products.",
      // "Collaborated closely with designers, backend developers and product teams.",
      // "Focused on performance, responsive design and maintainable frontend architecture.",
      "Developed reusable and scalable React.js components using React Hooks, improving UI consistency, maintainability and development efficiency.",
      "Built responsive, mobile-first user interfaces using HTML5, CSS3, Sass, Bootstrap, Tailwind CSS and Material UI across desktop, tablet and mobile devices.",
      "Developed applications using Next.js, implementing routing and static page generation for scalable web experiences.",
      "Implemented client-side state management using Redux and Context API, improving application data flow and component communication.",
      "Integrated RESTful APIs and implemented authentication, authorization and role-based access control (RBAC) for secure application workflows.",
      "Developed reusable UI patterns and component abstractions to support scalable frontend architecture and consistent user experiences.",
      // "Collaborated with backend developers, UI/UX designers and stakeholders to translate business requirements into production-ready React applications.",
      "Used Git, NPM, Webpack and SonarQube for source control, build management and code-quality processes.",
      "Optimized frontend performance through code splitting, lazy loading, component optimization and bundle analysis, improving application responsiveness.",
    ],
    technologies: [
      "React.js",
      "JavaScript",
      "TypeScript",
      "Next.js",
      "Redux",
      "Context API",
      "Rest API",
      "RBAC",
      "Authentication",
      "JWT token",
      "CI/CD",
      "React Hooks",
      "React-Admin",
      "Tailwind CSS",
      "HTML5",
      "CSS3",
      "SonarQube",
      "Webpack",
    ],
  },
  {
    period: "Jul 2019 — Oct 2019",
    role: "Senior Software Engineer",
    company: "Prolim Solutions",
    location: "Bangalore",
    description:
      "Developed responsive web applications and interactive user interfaces while working closely with product and design teams.",
    achievements: [
      "Converted design concepts into responsive, cross-browser compatible interfaces",
      "Converted complex designs into responsive and accessible interfaces.",
      "Integrated APIs and enhanced functionality for usability and performance",
      "Collaborated with the development team to resolve UI issues",
    ],
    technologies: [
      "React.js",
      "JavaScript",
      "Rest API",
      "HTML5",
      "CSS",
      "Bootstrap",
      "WCAG",
      "NPM",
      "Webpack",
      "Github",
    ],
  },
  {
    period: "Apr 2016 — Mar 2019",
    role: "Senior UI Developer",
    company: "LMS Solutions",
    location: "Indore",
    description:
      "Started my professional frontend journey building responsive websites and web applications while developing strong foundations in modern web technologies.",
    achievements: [
      "Developed responsive web interfaces using HTML, CSS and JavaScript.",
      "Implemented reusable UI components and cross-browser compatible layouts.",
      "Collaborated with designers and backend developers to deliver client-facing web features.",
      "Delivered new features and improved existing interfaces for optimal performance.",
    ],
    technologies: [
      "React.js",
      "JavaScript",
      "HTML",
      "CSS",
      "SASS",
      "Bootstrap",
      "Material UI",
      "Responsive Design",
      "Flex-box",
      "CSS-grid",
      "Reusable UI Components",
      "Cross-Browser compatibility",
    ],
  },
  {
    period: "Jan 2014 — Jun 2015",
    role: "UI Developer",
    company: "CXS Media",
    location: "Indore",
    description:
      "Started my professional frontend journey building responsive websites and web applications while developing strong foundations in modern web technologies.",
    achievements: [
      "Built responsive websites using HTML, CSS and JavaScript.",
      "Implemented mobile-first designs and improved cross-browser compatibility",
      "Worked across desktop, tablet and mobile experiences.",
      "Collaborated with designers for accurate UI requirement implementation",
    ],
    technologies: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "JavaScript",
      "jQuery",
      "WordPress",
      "Responsive Design",
      "Cross-Browser compatibility",
    ],
  },
];
